blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', cache_page(180)(BlogListView.as_view()), name='list'),
    path('post/<int:pk>/', cache_page(180)(BlogDetailView.as_view()), name='post_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('users/', include('users.urls', namespace='users')),
                  path('customers/', include('customers.urls', namespace='customers')),
                  path('mailings/', include('mailings.urls', namespace='mailings')),
                  path('blog/', include('blog.urls', namespace='blog'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from mailings.apps import MailingsConfig
from mailings.views import MailingListView, MailingCreateView, MailingUpdateView, MailingDetailView, MailingDeleteView, \
    MailingSettingsUpdateView, MailingLogsListView, MessageCreateView, MessageListView, MessageDetailView, \
    MessageUpdateView, MessageDeleteView

app_name = MailingsConfig.name

urlpatterns = [
    path('', MailingListView.as_view(), name='list'),
    path('add/', MailingCreateView.as_view(), name='add'),
    path('edit/<int:pk>/', MailingUpdateView.as_view(), name='update'),
    path('<int:pk>/', MailingDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='delete'),
    path('settings/<int:pk>', MailingSettingsUpdateView.as_view(), name='detail_settings'),
    path('logs/', MailingLogsListView.as_view(), name='logs'),

    path('mail_create/', MessageCreateView.as_view(), name='mail_create'),
    path('mail_list/', MessageListView.as_view(), name='mail_list'),
    path('mail/<int:pk>/', MessageDetailView.as_view(), name='mail_detail'),
    path('mail/update/<int:pk>', MessageUpdateView.as_view(), name='mail_update'),
    path('mail/delete/<int:pk>', MessageDeleteView.as_view(), name='mail_delete'),
]

mailings/models.py
from django.db import models

from customers.models import Customer
from users.models import User

NULLABLE = {'blank': True, 'null': True}

MAILING_STATUS_CHOICES = (
    ('created', 'Создана'),
    ('enabled', 'Активна'),
    ('disabled', 'Неактивна')
)

MAILING_PERIOD_CHOICES = (
    ('every_minute', 'Каждую минуту'),
    ('daily', 'Ежедневно'),
    ('weekly', 'Еженедельно'),
    ('monthly', 'Ежемесячно')

)


class Message(models.Model):
    subject = models.TextField(max_length=100, verbose_name='Тема рассылки')
    body = models.TextField(verbose_name='Содержание рассылки')

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'


class Mailing(models.Model):
    message = models.ForeignKey(Message, verbose_name='Сообщение', on_delete=models.CASCADE, default=None)
    customers = models.ManyToManyField(Customer, verbose_name='Клиенты')
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)

    start_time = models.DateTimeField(verbose_name='Дата начала рассылки', **NULLABLE)
    creation_date = models.DateTimeField(verbose_name='Дата создания', auto_now=True)
    interval = models.CharField(max_length=15, choices=MAILING_PERIOD_CHOICES, default='daily',
                                verbose_name='Периодичность')
    status = models.CharField(max_length=8, choices=MAILING_STATUS_CHOICES, default='enabled',
                              verbose_name='Статус рассылки')
    next_attempt = models.DateTimeField(verbose_name='Дата последней отправки', **NULLABLE)

    def __str__(self):
        return f'{self.message} ({self.start_time})'

    class Meta:
        ordering = ["pk"]
        verbose_name = ('Рассылка')
        verbose_name_plural = ('Рассылки')


class Logs(models.Model):
    # user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    last_attempt_time = models.DateTimeField(verbose_name='Последняя отправка рассылки', auto_now=True)
    status = models.CharField(max_length=6, verbose_name='Статус отправки рассылки')
    mailing = models.ForeignKey(Mailing, verbose_name='Рассылка', on_delete=models.CASCADE)
    error_message = models.TextField(verbose_name='Сообщение об ошибке', **NULLABLE)

    def __str__(self):
        return (f'{self.last_attempt_time} '
                f'{self.status} '
                f'{self.mailing} '
                f'{self.error_message}')

    class Meta:
        verbose_name = ('Лог')
        verbose_name_plural = ('Логи')

mailings/forms.py
from django import forms

from mailings.models import Mailing, Message

from users.forms import MixinForm


class MailingCreateForm(forms.ModelForm):
    """Форма создания рассылки"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            self.fields['start_time'].required = True
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Mailing
        exclude = ('user', 'send_datetime', 'next_attempt')
        widgets = {
            'start_time': forms.DateInput(attrs=dict(type='datetime-local'))
        }


class MailingSettingsUpdateForm(forms.ModelForm):
    """Форма обновления рассылки"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Mailing
        exclude = ('subject', 'body', 'user', 'next_attempt')


class MailingSettingsManagerUpdateForm(MailingSettingsUpdateForm):
    """Форма обновления настроек рассылки для менеджера"""

    subject = forms.CharField(disabled=True, label="Тема")
    body = forms.CharField(disabled=True, label="Содержание рассылки")
    start_time = forms.DateTimeField(disabled=True, label='Дата начала рассылки:')

    class Meta:
        model = Mailing
        exclude = ('user', 'customers', 'interval', 'next_attempt')


class MessageForm(MixinForm, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('owner',)

mailings/views.py
import calendar
from datetime import datetime, timedelta
from django.contrib.auth.mixins import UserPassesTestMixin
import pytz
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from mailings.forms import MailingCreateForm, MailingSettingsUpdateForm, MailingSettingsManagerUpdateForm, MessageForm

from mailings.models import Mailing, Logs, Message


class MailingListView(LoginRequiredMixin, ListView):
    """Контроллер отображения всех рассылок"""
    model = Mailing
    login_url = 'users:login'

    extra_context = {"title": "Рассылки"}

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailings.view_mailings'):
            return queryset
        else:
            queryset = queryset.filter(user=self.request.user.id)
            return queryset


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания рассылки """

    model = Mailing
    form_class = MailingCreateForm
    extra_context = {'title': 'Создать рассылку'}
    success_url = reverse_lazy('mailings:list')

    def dispatch(self, request, *args, **kwargs):
        """Метод переадресации пользователя, если он не прошел аутентификацию"""
        if not request.user.is_authenticated:
            return redirect('users:register')
        else:
            return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        """Метод получения данных из базы"""
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user.id)
        return queryset

    def form_valid(self, form):
        """Метод получения данных из формы"""
        current_time = datetime.now().replace(tzinfo=pytz.UTC)
        status = ''
        error_message = ''
        form.instance.user = self.request.user

        if form.is_valid():
            customers = form.cleaned_data['customers']
            new_mailing = form.save()
            if new_mailing.start_time > current_time:
                new_mailing.next_attempt = new_mailing.start_time
            else:
                if new_mailing.interval == 'every_minute':
                    new_mailing.next_attempt = new_mailing.start_time + timedelta(minutes=1)

                if new_mailing.interval == 'daily':
                    new_mailing.next_attempt = new_mailing.start_time + timedelta(days=1)

                if new_mailing.interval == 'weekly':
                    new_mailing.next_attempt = new_mailing.start_time + timedelta(days=7)

                if new_mailing.interval == 'monthly':
                    today = datetime.today()
                    days = calendar.monthrange(today.year, today.month)[1]
                    new_mailing.next_attempt = current_time + timedelta(days=days)

                for customer in customers:
                    new_mailing.customers.add(customer.pk)
                new_mailing.save()
                # send_mail_and_log(
                #     new_mailing=new_mailing,
                #     current_time=current_time,
                #     customers=customers,
                #     user=form.instance.user,
                #     status=status,
                #     error_message=error_message
                # )
        return super().form_valid(form)


class MailingDetailView(LoginRequiredMixin, DetailView):
    """Контроллер получения данных одной рассылки """

    login_url = 'users:register'
    redirect_field_name = 'register'
    model = Mailing

    def get_title(self):
        """Метод получения заголовка"""
        return self.object.title

    def get_queryset(self):
        """Метод получения данных из базы"""
        queryset = super().get_queryset()
        queryset = queryset.filter(id=self.kwargs.get('pk'))
        return queryset


class MailingUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """Контроллер обновления данных рассылки"""
    login_url = 'users:register'
    redirect_field_name = 'register'

    model = Mailing
    form_class = MailingCreateForm
    extra_context = {'title': 'Редактировать рассылку'}

    def has_permission(self):
        """Метод проверки разрешений пользователя"""
        object_ = self.get_object()
        user = self.request.user
        if object_.user == user:
            return object_
        else:
            raise PermissionError('Редактировать рассылки может только пользователь')

    def get_success_url(self):
        """Метод переадресации пользователя"""
        return reverse('mailings:list')

    def get_queryset(self):
        """Метод получения данных из базы"""
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    """Контроллер удаления рассылки"""
    login_url = 'users:register'
    redirect_filed_name = 'register'

    model = Mailing
    extra_context = {'title': 'Удалить рассылку'}
    success_url = reverse_lazy('mailings:list')

    def get_queryset(self):
        """Метод получения данных из базы"""
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user.id)
        return queryset


class MailingSettingsUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер обновления настроек рассылок"""
    login_url = 'users:register'
    redirect_filed_name = 'register'

    permission_required = ('mailings.change_mailings', 'mailings.view_mailings')

    model = Mailing
    form_class = MailingSettingsUpdateForm
    extra_context = {'title': 'Настроить рассылку'}
    success_url = reverse_lazy('mailings:list')
    template_name = 'mailings/mailing_settings_form.html'

    def has_permission(self):
        """Метод проверки прав пользователя"""
        object_ = self.get_object()
        user = self.request.user
        if object_.user == user or (user.is_staff and user.has_perms(self.permission_required)):
            return object_
        else:
            raise PermissionError('Редактировать настройки может только пользователь или менеджер')

    def get_form_class(self):
        """Метод выбора нужной формы для вывода,в зависимости от типа пользователя"""
        user = self.request.user
        if user.is_staff and user.has_perms(self.permission_required):
            return MailingSettingsManagerUpdateForm
        else:
            return MailingSettingsUpdateForm

    def get_queryset(self):
        """Метод получения данных из базы"""
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailings.update'):
            return queryset
        else:
            queryset = queryset.filter(user=self.request.user.id)
            return queryset

    def form_valid(self, form):
        """ Метод сохранения данных формы и отпправки рассылки"""
        current_time = datetime.now().replace(tzinfo=pytz.UTC)
        status = ''
        error_message = ''
        if form.has_changed():
            if self.request.user.is_staff:
                updated_settings = form.save()
                updated_settings.save()
            else:
                customers = form.cleaned_data['customers']
                updated_settings = form.save()

                if updated_settings.interval == 'every_minute':
                    updated_settings.next_attempt = current_time + timedelta(minutes=1)

                if updated_settings.interval == 'daily':
                    updated_settings.next_attempt = current_time + timedelta(days=1)

                elif updated_settings.interval == 'weekly':
                    updated_settings.next_attempt = current_time + timedelta(days=7)

                if updated_settings.interval == 'monthly':
                    today = datetime.today()
                    days = calendar.monthrange(today.year, today.month)[1]
                    updated_settings.next_attempt = current_time + timedelta(days=days)

                for customer in customers:
                    updated_settings.customers.add(customer.pk)
                updated_settings.save()
                form.instance.user = self.request.user
                # send_mail_and_log(
                #     new_mailing=updated_settings,
                #     current_time=current_time,
                #     customers=customers,
                #     user=form.instance.user,
                #     status=status,
                #     error_message=error_message
                # )

        return super().form_valid(form)


class MailingLogsListView(LoginRequiredMixin, ListView):
    """Контроллер отображения всех логов"""
    login_url = 'users:register'
    redirect_filed_name = 'register'

    model = Logs
    extra_context = {"title": "Логи рассылок"}
    template_name = 'mailings/mailing_logs_list.html'

    def get_queryset(self):
        """Метод получения данных из базы"""
        queryset = super().get_queryset()
        if not self.request.user.is_staff:
            queryset = queryset.filter(user=self.request.user.id)
        else:
            queryset = queryset.all()
        return queryset


class MessageCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailings:list')

    def form_valid(self, form):
        obj: Message = form.save()
        obj.owner = self.request.user
        obj.save()
        return super().form_valid(form)

    def test_func(self):
        return not self.request.user.is_staff


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        return Message.objects.filter(owner=self.request.user)


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message

mailings/templates/mailings/mailing_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12 mt-5 mb-5 text-center">
            <h2>{{ title }}</h2>
        </div>
        <div class="container text-center col-8">
                <form method="post" class="row" enctype="multipart/form-data">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                Удаление рассылки
                            </div>
                            <div class="card-body">
                                {% csrf_token %}
                                <p>Удалить рассылку "{{ object.subject }}"?</p>
                                <button type="submit" class="btn btn-danger text-white">
                                    Удалить
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
        </div>
    </div>
{% endblock %}

mailings/templates/mailings/mailing_detail.html
{% extends 'main/base.html' %}

{% block content %}
        <div class="col-9 mt-5 mb-5 text-center">
            <h2>Тема: <br>{{ object.subject }}</h2>
        </div>
        <div class="col-9 mt-5 mb-5 text-center">
                <p>Содержание рассылки: <br>{{ object.body }}</p>
        </div>
        <div class="col-9 mt-5 mb-5 text-center">
                <p>
                    Подписанные клиенты:
                </p>
                {% for customer in object.customers.all %}
                    <p>
                    {{ customer.email }}
                    </p>
                {% endfor %}
                    Настройки:
            <p>
                <b>Дата начала рассылки: </b>{{ object.start_time }}
            </p>
            <p>
                <b>Периодичность: </b>{{ object.get_interval_display }}
            </p>
            <p>
                <b>Статус: </b>{{ object.get_status_display }}
            </p>

        </div>
{% endblock %}

mailings/templates/mailings/mailing_form.html
{% extends 'main/base.html' %}

{% block content %}
    <form method="post" class="row text-center" enctype="multipart/form-data">
        <div class="col-9 mt-5 mb-5">
                <h2>{{ title }}</h2>
                <div class="col-9 mt-1" >
                    <div class="card-body text-center">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                        <button type="submit" class="btn btn-primary text-white">
                            Сохранить
                        </button>
                        {% else %}
                        <button type="submit" class="btn btn-primary text-white">
                            Добавить
                        </button>
                        {% endif %}

                    </div>
                </div>
        </div>
    </form>
{% endblock %}

mailings/templates/mailings/mailing_list.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12 mt-5 mb-5 text-center">
            <h2>{{ title }}</h2>
        </div>
        <div class="col-12 mt-1" >
            <a class="btn btn-primary col-12 mb-5" href="{% url 'mailings:add' %}">
                Создать рассылку
            </a>
        </div>
        <div class="col-12 mt-1" >
            <div class="table-responsive">
                <table class="table align-middle">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Тема рассылки</th>
                            <th scope="col">Текст рассылки</th>
                            <th scope="col">Клиент</th>
                            <th scope="col">Статус</th>
                            <th class="w-25" scope="col">Действия</th>
                        </tr>
                    </thead>
                    {% for object in object_list %}
                        <tbody>
                            <tr>
                              <th scope="row">{{ object.id }}</th>
                              <td>
                                  <a href="{% url 'mailings:detail' object.id %}">
                                  {{ object.subject }}
                                  </a>
                              </td>
                              <td>{{ object.body|truncatechars:50 }}</td>
                                <td>
                                    {% for customer in object.customers.all %}
                                        {% if object.customers.all|length > 1 %}
                                        {{ customer.email }},
                                        {% else %}
                                        {{ customer.email }}
                                        {% endif %}
                                    {% endfor %}
                                </td>
                                <td>
                                    {{ object.get_status_display }}
                                </td>
                                <td>
                                    <a class="btn btn-primary" href="{% url 'mailings:detail_settings' object.pk %}">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         width="16" height="16"
                                         fill="currentColor"
                                         class="bi bi-gear-wide-connected"
                                         viewBox="0 0 16 16">
                                        <path d="M7.068.727c.243-.97 1.62-.97 1.864 0l.071.286a.96.96 0 0 0 1.622.434l.205-.211c.695-.719 1.888-.03 1.613.931l-.08.284a.96.96 0 0 0 1.187 1.187l.283-.081c.96-.275 1.65.918.931 1.613l-.211.205a.96.96 0 0 0 .434 1.622l.286.071c.97.243.97 1.62 0 1.864l-.286.071a.96.96 0 0 0-.434 1.622l.211.205c.719.695.03 1.888-.931 1.613l-.284-.08a.96.96 0 0 0-1.187 1.187l.081.283c.275.96-.918 1.65-1.613.931l-.205-.211a.96.96 0 0 0-1.622.434l-.071.286c-.243.97-1.62.97-1.864 0l-.071-.286a.96.96 0 0 0-1.622-.434l-.205.211c-.695.719-1.888.03-1.613-.931l.08-.284a.96.96 0 0 0-1.186-1.187l-.284.081c-.96.275-1.65-.918-.931-1.613l.211-.205a.96.96 0 0 0-.434-1.622l-.286-.071c-.97-.243-.97-1.62 0-1.864l.286-.071a.96.96 0 0 0 .434-1.622l-.211-.205c-.719-.695-.03-1.888.931-1.613l.284.08a.96.96 0 0 0 1.187-1.186l-.081-.284c-.275-.96.918-1.65 1.613-.931l.205.211a.96.96 0 0 0 1.622-.434l.071-.286zM12.973 8.5H8.25l-2.834 3.779A4.998 4.998 0 0 0 12.973 8.5zm0-1a4.998 4.998 0 0 0-7.557-3.779l2.834 3.78h4.723zM5.048 3.967c-.03.021-.058.043-.087.065l.087-.065zm-.431.355A4.984 4.984 0 0 0 3.002 8c0 1.455.622 2.765 1.615 3.678L7.375 8 4.617 4.322zm.344 7.646.087.065-.087-.065z"/>
                                    </svg>
                                    </a>
                                    {% if not user.is_staff %}
                                    <a class="btn btn-primary" href="{% url 'mailings:update' object.pk %}">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             width="16"
                                             height="16"
                                             fill="currentColor"
                                             class="bi bi-pencil"
                                             viewBox="0 0 16 16">
                                            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                        </svg>
                                    </a>
                                    <a class="btn btn-danger" href="{% url 'mailings:delete' object.pk %}">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             width="16"
                                             height="16"
                                             fill="currentColor"
                                             class="bi bi-pencil"
                                             viewBox="0 0 16 16">
                                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                                        </svg>
                                    </a>
                                    {% endif %}
                                </td>
                            </tr>
                        </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

mailings/templates/mailings/mailing_logs_list.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12 mt-5 mb-5 text-center">
            <h2>{{ title }}</h2>
        </div>
        <div class="col-12 mt-1" >
            <div class="table-responsive">
                <table class="table align-middle">
                    <thead>
                        <tr>
                            <th scope="col">Тема рассылки</th>
                            <th scope="col">Последняя отправка рассылки</th>
                            <th scope="col">Статус</th>
                            <th scope="col">Сообщение ошибки</th>
                        </tr>
                    </thead>
                    {% for object in object_list %}
                        <tbody>
                            <tr>
                                <td>{{ object.mailing.subject|truncatechars:30 }}</td>
                                <td>{{ object.last_attempt_time }}</td>
                                <td>{{ object.status }}</td>
                                <td>{{ object.error_message }}</td>
                            </tr>
                        </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

mailings/templates/mailings/mailing_message_form.html
{% extends 'main/base.html' %}

{%  block content %}

<div class="col-lg-10">
    <div class="content">
        <h1 class="card-title text-center mt-5">Adding new message</h1>
        <h3 class="card-title text-center mt-1">You can create new message here</h3>

        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-lg-6">
{#                    <h2 class="text-center">Write here</h2>#}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
{#                <div class="col-lg-6">#}
{#                    <h2 class="text-center">Attention</h2>#}
{#                    <div class="text-center">#}
{#                        <p>You can add new mailing list here</p>#}
{#                        <p>be careful, choose correct message</p>#}
{#                        <p>in case of emergency write to</p>#}
{#                        <p>Email: info@example.com</p>#}
{#                        <p>If you can't find message what you need to send,</p>#}
{#                        <p>You have to create a new one</p>#}
{#                        <a href="{% url 'main:massage_create' %}" class="btn btn-danger">Create</a>#}
{#                    </div>#}
{#                </div>#}
            </div>
        </div>
    </div>
</div>
{%  endblock %}

mailings/templates/mailings/mailing_settings_form.html
{% extends 'main/base.html' %}

{% block content %}
    <form method="post" class="row text-center" enctype="multipart/form-data">
        <div class="col-9 mt-5 mb-5">
                <h2>{{ title }}</h2>
                <div class="col-9 mt-1" >
                    <div class="card-body text-center">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                        <button type="submit" class="btn btn-primary text-white">
                            Сохранить
                        </button>
                        {% else %}
                        <button type="submit" class="btn btn-primary text-white">
                            Добавить
                        </button>
                        {% endif %}

                    </div>
                </div>
        </div>
    </form>
{% endblock %}