blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', cache_page(180)(BlogListView.as_view()), name='list'),
    path('post/<int:pk>/', cache_page(180)(BlogDetailView.as_view()), name='post_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('users/', include('users.urls', namespace='users')),
                  path('customers/', include('customers.urls', namespace='customers')),
                  path('mailings/', include('mailings.urls', namespace='mailings')),
                  path('blog/', include('blog.urls', namespace='blog'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path

from customers.apps import CustomersConfig
from customers.views import CustomerListView, CustomerCreateView, CustomerUpdateView, CustomerDeleteView

app_name = CustomersConfig.name

urlpatterns = [
    path('customers/', CustomerListView.as_view(), name='list'),
    path('customers/add/', CustomerCreateView.as_view(), name='add'),
    path('customers/edit/<int:pk>/', CustomerUpdateView.as_view(), name='update'),
    path('customers/delete/<int:pk>/', CustomerDeleteView.as_view(), name='delete'),
]

customers/models.py
from django.db import models

# from mailings.models import Mailing
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Customer(models.Model):
    first_name = models.CharField(max_length=255, verbose_name='Имя', **NULLABLE)
    last_name = models.CharField(max_length=255, verbose_name='Фамилия', **NULLABLE)
    email = models.EmailField(max_length=255, verbose_name='email', unique=False)
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    owner = models.ManyToManyField(User, verbose_name='Пользователь')

    # mailing = models.ManyToManyField(Mailing, verbose_name='Рассылка')

    def __str__(self):
        return f'{self.email} {self.first_name} {self.last_name}'

    class Meta:
        verbose_name = ('Клиент')
        verbose_name_plural = ('Клиенты')

customers/forms.py
from django import forms

from customers.models import Customer


class CustomerCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Customer
        exclude = ['owner']
        # fields = '__all__'

customers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from customers.forms import CustomerCreateForm
from customers.models import Customer


class CustomerListView(LoginRequiredMixin, ListView):
    """Контроллер вывода списка всех клиентов"""
    model = Customer
    login_url = 'users:login'

    extra_context = {"title": "Клиенты"}


class CustomerCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания клиента"""

    model = Customer
    form_class = CustomerCreateForm
    extra_context = {'title': 'Добавить клиента'}
    success_url = reverse_lazy('customers:list')

    def get_context_data(self, **kwargs):
        """Метод получения контекста"""
        context_data = super().get_context_data()
        user = self.request.user
        context_data['user'] = user
        return context_data

    def form_valid(self, form):
        """Метод получения данных из формы"""
        if form.is_valid():
            user = self.request.user
            new_customer = form.save()
            new_customer.owner.add(user)
            new_customer.save()
            return super().form_valid(form)


class CustomerUpdateView(UpdateView):
    """Контроллер обновления клиента"""
    model = Customer
    form_class = CustomerCreateForm
    extra_context = {'title': 'Редактировать клиента'}

    def get_success_url(self):
        """Метод переадресации после создания пользователя"""
        return reverse('customers:list')


class CustomerDeleteView(DeleteView):
    """Контроллер удаления клиента"""
    model = Customer
    extra_context = {'title': 'Удалить клиента'}
    success_url = reverse_lazy('customers:list')

customers/templates/customers/customer_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12 mt-5 mb-5 text-center">
            <h2>{{ title }}</h2>
        </div>
        <div class="container text-center col-8">
                <form method="post" class="row" enctype="multipart/form-data">

                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                Удаление клиента
                            </div>
                            <div class="card-body">
                                {% csrf_token %}
                                <p>Удалить клиента "{{ object.email }}"?</p>
                                <button type="submit" class="btn btn-danger text-white">
                                    Удалить
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
{% endblock %}

customers/templates/customers/customer_form.html
{% extends 'main/base.html' %}

{% block content %}
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="col-12 mt-5 mb-0 text-center">
            <h2>{{ title }}</h2>
        </div>
        <div class="col-2"></div>
             <div class="col-8 mt-0" >
                    <div class="card-body text-center">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                        <button type="submit" class="btn btn-primary text-white">
                            Сохранить
                        </button>
                        {% else %}
                        <button type="submit" class="btn btn-primary text-white">
                            Добавить
                        </button>
                        {% endif %}
                    </div>
                </div>
                </div>
    </form>
{% endblock %}

customers/templates/customers/customer_list.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12 mt-5 mb-5 text-center">
            <h2>{{ title }}</h2>
        </div>
        <div class="col-12 mt-1 text-center" >
        <a class="btn btn-primary col-12 mb-5" href="{% url 'customers:add' %}">
            Добавить клиента
        </a>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Имя</th>
                    <th scope="col">Фамилия</th>
                    <th scope="col">Email</th>
                    <th scope="col">Действия</th>
                </tr>
                </thead>
                {% for object in object_list %}
                    <tbody>
                        <tr>
                            <td>{{ object.id }}</td>
                            <td>{{ object.first_name }}</td>
                            <td>{{ object.last_name }}</td>
                            <td>{{ object.email }}</td>
                            <td>
                                <a class="btn btn-primary" href="{% url 'customers:update' object.pk %}">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         width="16"
                                         height="16"
                                         fill="currentColor"
                                         class="bi bi-pencil"
                                         viewBox="0 0 16 16">
                                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                    </svg>
                                </a>
                                <a class="btn btn-danger" href="{% url 'customers:delete' object.pk %}">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         width="16"
                                         height="16"
                                         fill="currentColor"
                                         class="bi bi-pencil"
                                         viewBox="0 0 16 16">
                                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>                                    </svg>
                                </a>
                            </td>
                        </tr>
                    </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}