blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', cache_page(180)(BlogListView.as_view()), name='list'),
    path('post/<int:pk>/', cache_page(180)(BlogDetailView.as_view()), name='post_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('users/', include('users.urls', namespace='users')),
                  path('customers/', include('customers.urls', namespace='customers')),
                  path('mailings/', include('mailings.urls', namespace='mailings')),
                  path('blog/', include('blog.urls', namespace='blog'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.service_users import generate_new_password
from users.views import LoginView, LogoutView, UserProfileView, RegisterView, \
    UserConfirmEmailView, EmailConfirmationSentView, EmailConfirmedView, \
    EmailConfirmationFailedView, UserUpdateView, EmailSendingError, UsersListView, UsersManagerUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/sending_failed', EmailSendingError.as_view(), name='sending_error'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/edit', UserUpdateView.as_view(), name='edit_profile'),
    path('profile/generate_password/', generate_new_password, name='generate_password'),
    path('profile/verify_email/<str:verification_code>/', UserConfirmEmailView.as_view(), name='verify_email'),
    path('profile/verification_link_sent/', EmailConfirmationSentView.as_view(), name='verification_link_sent'),
    path('profile/email_verified/', EmailConfirmedView.as_view(), name='email_verified'),
    path('profile/verification_failed/', EmailConfirmationFailedView.as_view(), name='verification_failed'),
    path('users/list/', UsersListView.as_view(), name='list'),
    path('users/edit/<int:pk>', UsersManagerUpdateView.as_view(), name='manager_update')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Email')
    first_name = models.CharField(max_length=250, verbose_name='Имя', **NULLABLE)
    last_name = models.CharField(max_length=250, verbose_name='Фамилия', **NULLABLE)
    verification_code = models.CharField(max_length=256, verbose_name='Код проверки', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name="Пользователь активен")

    # переопределение поля юзернейма
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.first_name} {self.last_name} {self.email}'

    class Meta:
        verbose_name = ('Пользователь')
        verbose_name_plural = ('Пользователи')

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm

from users.models import User


class MixinForm:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserForm(UserCreationForm):
    """
    Форма регистрации пользователя
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = User
        fields = (
            'email',
            'password1',
            'password2',
            'first_name',
            'last_name',
        )


class UserProfileForm(UserChangeForm):
    """
    Форма обновления данных пользователя
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
        )
        exclude = ('password',)


class UserManagerForm(UserProfileForm):
    """
    Форма настройки активации пользователя для менеджера
    """
    email = forms.CharField(disabled=True, label="Email")
    first_name = forms.CharField(disabled=True, label="Имя")
    last_name = forms.CharField(disabled=True, label="Фамилия")

    class Meta:
        model = User

        exclude = (
            'last_login',
            'is_superuser',
            'groups',
            'user_permissions',
            'is_staff',
            'date_joined',
            'verification_code',
            'password',
            'password1',
            'password2',
        )

users/views.py
from smtplib import SMTPException

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.shortcuts import redirect, resolve_url, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, ListView, TemplateView, UpdateView

from users.forms import CustomAuthenticationForm, UserForm, UserProfileForm, UserManagerForm
from users.models import User
from users.service_users import code_generator, send_verification_link, password_generator, send_new_password


class LoginView(BaseLoginView):
    template_name = 'users/login.html'
    form_class = CustomAuthenticationForm


class LogoutView(BaseLogoutView):
    template_name = 'users/login.html'


class RegisterView(CreateView):
    """
    Контроллер регистрации пользователя
    """
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'
    extra_context = {
        'title': 'Регистрация'}

    def form_valid(self, form):
        """Метод получения данных формы"""
        generated_code = code_generator(6)
        user = form.save()
        user.is_active = False
        user.verification_code = generated_code

        verification_code = str(generated_code) + str(user.pk)
        activation_url = self.request.build_absolute_uri(
            reverse_lazy(
                'users:verify_email', kwargs={
                    'verification_code': verification_code
                }
            )
        )
        try:
            send_verification_link(activation_url, user.email)
            user.save()
            return redirect('users:verification_link_sent')
        except SMTPException as e:
            user.delete()
            return redirect('users:sending_error')


class EmailSendingError(TemplateView):
    """Контроллер вывода страницы в случае неудачной отправки письма"""
    template_name = 'users/email_sending_failed.html'
    extra_context = {
        'title': 'Ошибка'}


class UserConfirmEmailView(View):
    """Контрллер подтверждения регистрации по ссылке"""

    def get(self, request, verification_code):
        """Метод проверки валидность ссылки потдверждения регистрации"""
        uid = int(verification_code[6:])
        code = verification_code[:6]
        try:
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and code == user.verification_code:
            user.is_active = True
            user.verification_code = ""
            user.save()
            return redirect(reverse_lazy('users:email_verified'))
        else:
            return redirect(reverse_lazy('users:verification_failed'))


class EmailConfirmationSentView(TemplateView):
    """Контроллер вывода страницы уведомления об отправке письма"""
    template_name = 'users/verification_link_sent.html'
    extra_context = {
        'title': 'Подтверждение почты'}


class EmailConfirmedView(TemplateView):
    """Контроллер вывода страницы подтвреждения регистрации"""
    template_name = 'users/email_verified.html'
    extra_context = {
        'title': 'Подтверждение почты'}


class EmailConfirmationFailedView(TemplateView):
    """Контроллер вывода страницы подтвреждения регистрации"""

    template_name = 'users/verification_failed.html'
    extra_context = {
        'title': 'Подтверждение почты'}


class UserProfileView(LoginRequiredMixin, ListView):
    """Контроллер отображения профиля пользователя"""
    login_url = 'users:login'
    template_name = 'users/profile.html'
    model = User
    extra_context = {"title": "Профиль"}

    def get_context_data(self, *args, **kwargs):
        """Методы передачи в контекст объекта пользователя"""
        context_data = super().get_context_data(*args, **kwargs)
        user = self.request.user
        context_data['user'] = user
        return context_data


class UserUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер обновления данных пользователя
    """
    model = User
    success_url = reverse_lazy('users:profile')
    extra_context = {
        'title': 'Профиль'
    }
    form_class = UserProfileForm

    def get_object(self, queryset=None):
        return self.request.user


class UsersListView(LoginRequiredMixin, ListView):
    """Контроллер вывода списка всех пользователей для менеджера"""
    login_url = 'users:register'
    redirect_field_name = 'register'

    model = User
    extra_context = {'title': 'Пользователи'}
    template_name = 'users/users_list.html'

    def get_queryset(self):
        """Метод получения данных из базы"""
        queryset = super().get_queryset()
        if self.request.user.is_staff:
            return queryset


class UsersManagerUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """Контроллер управления пользователями для менеджера (активация/деактивация)"""
    login_url = 'users:register'
    redirect_field_name = 'register'
    template_name = 'users/user_form.html'
    success_url = reverse_lazy('users:list')

    permission_required = ('users.change_users', 'users.view_users')

    model = User
    extra_context = {'title': 'Активация пользователя'}

    def has_permission(self):
        """Метод проверки прав пользователя"""
        object_ = self.get_object()
        user = self.request.user
        if user.is_staff and user.has_perms(self.permission_required):
            return object_
        else:
            raise PermissionError('Редактировать статус пользователя может только менеджер')

    def get_form_class(self):
        """Метод вывода формы управления пользователем для менеджера"""
        user = self.request.user
        if user.is_staff and user.has_perms(self.permission_required):
            return UserManagerForm

    def form_valid(self, form):
        """Метод получения данных из формы"""
        if form.has_changed():
            user = get_object_or_404(User, id=self.kwargs['pk'])
            if user.is_active:
                user.is_active = False
            else:
                user.is_active = True

            user.save()
        return super().form_valid(form)

users/templates/users/email_sending_failed.html
{% extends 'main/base.html' %}
{% block content %}

<div class="row mt-5 mb-5">
        <div class="col-2">
        </div>
        <div class="container text-left col-9 mt-5">
        <div class="col-9">
            <div class="card">
                <div class="card-header">
                    Ошибка отправки письма
                </div>
                    <div class="card-body">
                            При отправке письма произошла ошибка, попробуйте позднее
                    </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/email_verified.html
{% extends 'main/base.html' %}
{% block content %}

<div class="row mt-5 mb-5">
        <div class="col-2">
        </div>
        <div class="container text-left col-9 mt-5">
        <div class="col-9">
            <div class="card">
                <div class="card-header">
                    Подтверждение электронной почты
                </div>
                    <div class="card-body">
                            Ваша электронная почта подтверждена
                    </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'main/base.html' %}


{% block content %}
<div class="row mt-5 mb-5">
        <div class="col-3">
        </div>
        <div class="container text-left col-9 mt-5">
        <div class="col-6">
            <div class="card">
                <form method="post">
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                Вход
                            </button>
                    <a class="btn btn-primary" href="{% url 'users:register' %}" type="button">Зарегистрироваться</a>
                    </div>
                </form>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/profile.html
{%  extends 'main/base.html' %}

{% block content %}
<div class="jumbotron bg-transparent"></div>

    <div class="container overflow-hidden text-center">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="p-6">
                    <div class="card">
                        <div class="card-header">
                            <h3>Профиль</h3>
                        </div>
                        <div class="card-body text-left">
                              <h6>Имя:</h6>
                              <p class="fw-bold">{{user.first_name}}</p>
                              <h6>Фамилия:</h6>
                              <p class="fw-bold">{{user.last_name}}</p>
                              <h6>Email:</h6>
                              <p class="fw-bold">{{user.email }}</p>
                        </div>
                        <div class="card-footer">
                            <a class="btn btn-primary" href="{% url 'users:edit_profile' %}" type="button">
                                Редактировать
                            </a>
                            <a class="btn btn-warning" href="{% url 'users:logout' %}" type="button">
                                Выйти
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%  endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}


{% block content %}
<div class="row mt-5 mb-5">
        <div class="col-2">
        </div>
        <div class="container text-left col-9 mt-5">
        <div class="col-9">
            <div class="card">
                <form method="post">
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                    </div>
                </form>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row mt-5 mb-5">
        <div class="col-2">
        </div>
        <div class="container text-left col-9 mt-5">
        <div class="col-9">
            <div class="card">
                <form method="post" enctype="multipart/form-data">
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                Сохранить
                            </button>
                        {% if not request.user.is_staff %}
                            <a class="btn btn-warning" href="{% url 'users:generate_password' %}">
                                Сгенерировать новый пароль
                            </a>
                        {% endif %}
                    </div>
                </form>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/users_list.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12 mt-5 mb-5 text-center">
            <h2>{{ title }}</h2>
        </div>
        <div class="col-12 mt-1" >
            <div class="table-responsive">
                <table class="table align-middle text-center">
                    <thead>
                        <tr>
                            <th scope="col">id Пользователя</th>
                            <th scope="col">Имя</th>
                            <th scope="col">Фамилия</th>
                            <th scope="col">Почта</th>
                            <th scope="col">Статус</th>
                            <th class="w-25" scope="col">Действия</th>
                        </tr>
                    </thead>
                    {% for object in object_list %}
                        <tbody>
                            <tr>
                              <td>{{ object.pk }}</td>
                              <td>{{ object.first_name }}</td>
                              <td>{{ object.last_name }}</td>
                              <td>{{ object.email }}</td>
                                {% if object.is_active == True %}
                                    <td>Активен</td>
                                {% else %}
                                    <td>Неактивен</td>
                                {% endif %}
                                <td>
                                    <a class="btn btn-primary" href="{% url 'users:manager_update' object.pk %}">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             width="16"
                                             height="16"
                                             fill="currentColor"
                                             class="bi bi-pencil"
                                             viewBox="0 0 16 16">
                                            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                        </svg>
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/verification_failed.html
{% extends 'main/base.html' %}
{% block content %}

<div class="row mt-5 mb-5">
        <div class="col-2">
        </div>
        <div class="container text-left col-9 mt-5">
        <div class="col-9">
            <div class="card">
                <div class="card-header">
                    Ошибка подтверждения адреса почты
                </div>
                    <div class="card-body">
                            Ссылка для подтверждения по электронной почте недействительна
                    </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/verification_link_sent.html
{% extends 'main/base.html' %}
{% block content %}

<div class="row mt-5 mb-5">
        <div class="col-2">
        </div>
        <div class="container text-left col-9 mt-5">
        <div class="col-9">
            <div class="card">
                <div class="card-header">
                    Ссылка для подтверждения почты отправлена
                </div>
                    <div class="card-body">
                            Пожалуйста, подтвердите адрес электронной почты
                    </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}