blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/', cache_page(180)(BlogListView.as_view()), name='list'),
    path('post/<int:pk>/', cache_page(180)(BlogDetailView.as_view()), name='post_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('users/', include('users.urls', namespace='users')),
                  path('customers/', include('customers.urls', namespace='customers')),
                  path('mailings/', include('mailings.urls', namespace='mailings')),
                  path('blog/', include('blog.urls', namespace='blog'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from mailings.apps import MailingsConfig
from mailings.views import MailingListView, MailingCreateView, MailingUpdateView, MailingDetailView, MailingDeleteView, \
    MailingSettingsUpdateView, MailingLogsListView, MessageCreateView, MessageListView, MessageDetailView, \
    MessageUpdateView, MessageDeleteView

app_name = MailingsConfig.name

urlpatterns = [
    path('', MailingListView.as_view(), name='list'),
    path('add/', MailingCreateView.as_view(), name='add'),
    path('edit/<int:pk>/', MailingUpdateView.as_view(), name='update'),
    path('<int:pk>/', MailingDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='delete'),
    path('settings/<int:pk>', MailingSettingsUpdateView.as_view(), name='detail_settings'),
    path('logs/', MailingLogsListView.as_view(), name='logs'),

    path('mail_create/', MessageCreateView.as_view(), name='mail_create'),
    path('mail_list/', MessageListView.as_view(), name='mail_list'),
    path('mail/<int:pk>/', MessageDetailView.as_view(), name='mail_detail'),
    path('mail/update/<int:pk>', MessageUpdateView.as_view(), name='mail_update'),
    path('mail/delete/<int:pk>', MessageDeleteView.as_view(), name='mail_delete'),
]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import IndexView

app_name = MainConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index')
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.service_users import generate_new_password
from users.views import LoginView, LogoutView, UserProfileView, RegisterView, \
    UserConfirmEmailView, EmailConfirmationSentView, EmailConfirmedView, \
    EmailConfirmationFailedView, UserUpdateView, EmailSendingError, UsersListView, UsersManagerUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/sending_failed', EmailSendingError.as_view(), name='sending_error'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/edit', UserUpdateView.as_view(), name='edit_profile'),
    path('profile/generate_password/', generate_new_password, name='generate_password'),
    path('profile/verify_email/<str:verification_code>/', UserConfirmEmailView.as_view(), name='verify_email'),
    path('profile/verification_link_sent/', EmailConfirmationSentView.as_view(), name='verification_link_sent'),
    path('profile/email_verified/', EmailConfirmedView.as_view(), name='email_verified'),
    path('profile/verification_failed/', EmailConfirmationFailedView.as_view(), name='verification_failed'),
    path('users/list/', UsersListView.as_view(), name='list'),
    path('users/edit/<int:pk>', UsersManagerUpdateView.as_view(), name='manager_update')
]

main/views.py
import random

from django.core.cache import cache

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from blog.models import Blog
from customers.models import Customer
from mailings.models import Mailing


class IndexView(LoginRequiredMixin, TemplateView):
    """Контроллер вывода главной страницы"""
    login_url = 'users:login'
    template_name = 'index.html'
    extra_context = {
        'title': 'Главная страница'
    }

    def get_context_data(self, *args, **kwargs):
        """Метод получения контекста"""
        user = self.request.user
        if self.request.method == 'GET':
            if settings.CACHE_ENABLED:
                key = f'cached_statistics'
                cached_context = cache.get(key)
                if cached_context is None:
                    context = super().get_context_data(*args, **kwargs)
                    if not user.is_staff:
                        context['mailing_count'] = Mailing.objects.filter(user=user).count()
                        context['enabled_mailing'] = Mailing.objects.filter(user=user).filter(status='enabled').count()
                        context['unique_users'] = Customer.objects.filter(owner=user).distinct('email').count()
                    else:
                        context['mailing_count'] = Mailing.objects.all().count()
                        context['enabled_mailing'] = Mailing.objects.all().filter(status='enabled').count()
                        context['unique_users'] = Customer.objects.all().distinct('email').count()
                        main_page_context = {
                            'mailing_count': context['mailing_count'],
                            'enabled_mailing': context['enabled_mailing'],
                            'unique_users': context['unique_users']
                        }
                        cache.set(key, main_page_context)
                        all_blog_posts = Blog.objects.all()
                        random_posts = random.sample(list(all_blog_posts), 3)
                        context['three_random_posts'] = random_posts
                    return context
                else:
                    context = super().get_context_data(*args, **kwargs)
                    context['mailing_count'] = cached_context['mailing_count']
                    context['enabled_mailing'] = cached_context['enabled_mailing']
                    context['unique_users'] = cached_context['unique_users']
                    all_blog_posts = Blog.objects.all()
                    random_posts = random.sample(list(all_blog_posts), 3)
                    context['three_random_posts'] = random_posts
                return context

main/templates/base.html
{% load static %}

<!doctype html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>{{ title }}</title>

        <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    </head>

    <body>
    <main>
    <div class="container-fluid">
        <div class="row">
            <div class="col-2 mt-5">
                <div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary" style="width: 280px;">
                    <div class="heading-text text-primary text-left ml-lg-3">
                        <h2>Меню</h2>
                    </div>
                    <hr>
                    <ul class="nav nav-pills flex-column mb-auto">
                        <li class="nav-item">
                            <a href="{% url 'main:index' %}" class="nav-link link-body-emphasis">
                              Главная
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'users:profile' %}" class="nav-link link-body-emphasis">
                                Профиль
                            </a>
                        </li>
                        {% if request.user.is_staff %}
                        <li class="nav-item">
                            <a href="{% url 'users:list' %}" class="nav-link link-body-emphasis">
                                Пользователи
                            </a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a href="{% url 'customers:list' %}" class="nav-link link-body-emphasis">
                                Клиенты
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'mailings:list' %}" class="nav-link link-body-emphasis">
                                Рассылки
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'mailings:logs' %}" class="nav-link link-body-emphasis">
                                Логи
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'blog:list' %}" class="nav-link link-body-emphasis">
                                Блог
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- Переопределение блока содержимого страницы -->
            <div class="col-9">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    </main>

    </body>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</html>

main/templates/index.html
{% extends 'base.html' %}

{% load template_tags %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <div class="col-12 mt-5 mb-5">
                    <h2>{{ title }}</h2>
                </div>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-xs-12 mb-5">
                <div class="col-12 mt-0 mb-1">
                    <h4>Статистика</h4>
                </div>
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Всего рассылок</h5>
                        <h2>
                            <p class="card-text">{{ mailing_count  }}</p>
                        </h2>
                    </div>
                </div>
                    <div class="col-xs-12 mb-5 mt-5">
                        <div class="card" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">Активных рассылок</h5>
                                <h2><p class="card-text">{{ enabled_mailing }}</p></h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="card" style="width: 18rem;">
                                <div class="card-body">
                                    <h5 class="card-title">Уникальных клиентов</h5>
                                    <h2><p class="card-text">{{ unique_users }}</p></h2>
                                </div>
                        </div>
                    </div>
                </div>
            <div class="col-2"></div>
            <div class="col-xs-8">
                <div class="col-12 text-center">
                    <div class="col-12 mt-0 mb-1">
                        <h4>Случайные записи из блога</h4>
                    </div>
                    {% for post in three_random_posts %}
                        <div class="card mt-1" style="width: 30rem;">
                            <img src="{% mediapath post.thumbnail %}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ post.title }}</h5>
                                <p class="card-text">{{ post.content }}</p>
                                <a href="{% url 'blog:post_detail' post.pk %}" class="btn btn-primary">Подробнее</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}